---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by boge.
--- DateTime: 2020/9/24,0024 10:49
---


-- XML 2 TS

xmlTots_start_id = 1000
xmlTots_readXMLFile = "E:/WorkSpace/LayaBox/TypeScriptLib/assets/lib_str.xml"
xmlTots_writeXMLFile = "E:/WorkSpace/LayaBox/TypeScriptLib/assets/lib_str.xml"
xmlTots_writeTsFile = "E:/WorkSpace/LayaBox/TypeScriptLib/src/com/LibStr.ts"
xmlTots_namespaceName = "coreLib"



